# app.py
# =========================================================
# Creative Data Studio
# • VoicePainter (voice → color → poster)
# • Memory Atlas (weather → color → poster)
# =========================================================

import io
import random
import colorsys
import requests
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import librosa
from matplotlib.patches import Circle, Ellipse, Polygon, Rectangle

# ---------------------------------------------------------
# STREAMLIT CONFIG
# ---------------------------------------------------------
st.set_page_config(
    page_title="Creative Data Studio",
    page_icon="🎨",
    layout="wide"
)

# ---------------------------------------------------------
# SIDEBAR
# ---------------------------------------------------------
st.sidebar.title("🌐 Navigation")

page = st.sidebar.radio(
    "Select a page",
    ["Home", "VoicePainter", "MemoryAtlas"],
    format_func=lambda x: 
        "🏠 Home" if x == "Home" else
        "🎤 VoicePainter" if x == "VoicePainter" else
        "🌈 Memory Atlas"
)

st.sidebar.markdown("---")
st.sidebar.subheader("🔧 API Settings")
api_base = st.sidebar.text_input(
    "Open-Meteo API (default below):",
    value="https://api.open-meteo.com/v1/forecast"
)

st.sidebar.markdown("---")
st.sidebar.write("This app includes:")
st.sidebar.write("- Voice-based generative posters")
st.sidebar.write("- Weather → color → generative art")
st.sidebar.write("- Audio analysis")
st.sidebar.write("- Data-driven creativity")

# ---------------------------------------------------------
# UTIL
# ---------------------------------------------------------
def normalize(v, a, b):
    return float(np.clip((v - a) / (b - a + 1e-8), 0, 1))


# =========================================================
# HOME PAGE
# =========================================================
if page == "Home":
    st.title("🎨 Creative Data Studio")
    st.subheader("Art generated by **voice** and **weather data**")

    st.markdown("""
        This platform combines **generative art**,  
        **data visualization**, **audio processing**,  
        and **interactive web design**.

        Select a mode from the left sidebar:
        - 🎤 **VoicePainter**: Draw using your voice  
        - 🌈 **Memory Atlas**: Create posters from weather colors  
    """)

    st.image(
        "https://images.unsplash.com/photo-1500534623283-312aade485b7",
        use_container_width=True
    )


# =========================================================
# VOICEPAINTER PAGE
# =========================================================
elif page == "VoicePainter":
    st.title("🎤 VoicePainter: Draw with Your Voice")

    uploaded = st.file_uploader("Upload voice file (wav/mp3/m4a):",
                                type=["wav", "mp3", "m4a"])
    seed = st.slider("Poster variation seed", 0, 9999, 42)

    # -----------------------------
    # Extract audio features
    def extract_audio_features(file):
        y, sr = librosa.load(file, sr=None, mono=True)
        if len(y) > sr * 10:
            y = y[: sr * 10]

        rms = librosa.feature.rms(y=y)[0].mean()
        zcr = librosa.feature.zero_crossing_rate(y)[0].mean()
        centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0].mean()
        tempo, _ = librosa.beat.beat_track(y=y, sr=sr)

        try:
            f0 = librosa.yin(
                y,
                fmin=librosa.note_to_hz("C2"),
                fmax=librosa.note_to_hz("C7"),
            )
            pitch = float(np.nanmean(f0))
        except:
            pitch = 0.0

        return {
            "sr": sr,
            "pitch": pitch,
            "rms": rms,
            "zcr": zcr,
            "centroid": centroid,
            "tempo": float(tempo)
        }

    # -----------------------------
    # Palette
    def create_palette(f, n=5):
        p = normalize(f["pitch"], 80, 800)
        s = 0.4 + normalize(f["centroid"], 500, 5000) * 0.5
        l = 0.3 + normalize(f["rms"], 0, 0.1) * 0.4
        t = normalize(f["tempo"], 40, 180)
        z = normalize(f["zcr"], 0, 0.3)

        palette = []
        for i in range(n):
            h = (p + i * 0.12 + t * 0.3) % 1.0
            s2 = np.clip(s + (i - n//2) * 0.05, 0.2, 0.95)
            l2 = np.clip(l + (z - 0.5) * 0.2 + (i - n//2) * 0.03, 0.2, 0.85)
            palette.append(colorsys.hls_to_rgb(h, l2, s2))
        return palette

    # -----------------------------
    # Generative poster
    def draw_voice_poster(features, palette, seed):
        random.seed(seed)
        np.random.seed(seed)

        fig, ax = plt.subplots(figsize=(6, 9))
        ax.set_facecolor("black")
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        n_shapes = int(20 + normalize(features["rms"], 0, 0.1) * 40)

        for _ in range(n_shapes):
            color = random.choice(palette)
            cx, cy = np.random.rand(), np.random.rand()
            r = np.random.uniform(0.03, 0.15)

            if random.random() < 0.6:
                shape = Circle((cx, cy), r, color=color, alpha=0.8)
            else:
                w = r * np.random.uniform(0.4, 1.5)
                h = r * np.random.uniform(0.4, 1.5)
                angle = random.random() * 360
                shape = Ellipse((cx, cy), w, h, angle=angle,
                                color=color, alpha=0.8)

            ax.add_patch(shape)

        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=200, bbox_inches="tight")
        buf.seek(0)
        plt.close()
        return buf

    # -----------------------------
    # PROCESS
    if uploaded:
        st.audio(uploaded)

        uploaded.seek(0)
        f = extract_audio_features(uploaded)

        st.subheader("Audio Features")
        st.write(f)

        palette = create_palette(f)

        st.subheader("Color Palette")
        fig, ax = plt.subplots(figsize=(4, 1))
        for i, c in enumerate(palette):
            ax.add_patch(Rectangle((i, 0), 1, 1, color=c))
        ax.set_xlim(0, 5)
        ax.axis("off")
        st.pyplot(fig)

        st.subheader("Generated Voice Poster")
        poster = draw_voice_poster(f, palette, seed)
        st.image(poster, use_container_width=True)

        st.download_button("Download Poster", poster, "voice_poster.png")

    else:
        st.info("Upload a voice file to begin.")


# =========================================================
# MEMORY ATLAS PAGE
# =========================================================
elif page == "MemoryAtlas":
    st.title("🌈 Memory Atlas: Weather → Color → Generative Poster")

    city = st.text_input("City (English)", "Seoul")
    date = st.date_input("Select date")
    seed = st.slider("Poster variation (seed)", 0, 9999, 11)

    city_coords = {
        "Seoul": (37.5665, 126.9780),
        "Tokyo": (35.6895, 139.6917),
        "London": (51.5074, -0.1278),
        "Paris": (48.8566, 2.3522),
        "NYC": (40.7128, -74.0060)
    }
    lat, lon = city_coords.get(city, (37.5665, 126.9780))

    if st.button("Generate Memory Poster"):
        st.subheader("Fetching Weather Data...")

        url = (
            f"{api_base}?latitude={lat}&longitude={lon}"
            "&hourly=temperature_2m,relativehumidity_2m,cloudcover&timezone=auto"
        )

        try:
            data = requests.get(url).json()
            temp = np.mean(data["hourly"]["temperature_2m"])
            humidity = np.mean(data["hourly"]["relativehumidity_2m"])
            cloud = np.mean(data["hourly"]["cloudcover"])
        except:
            st.error("API request failed.")
            st.stop()

        # Metrics
        col1, col2, col3 = st.columns(3)
        col1.metric("Temp", f"{temp:.1f}°C")
        col2.metric("Humidity", f"{humidity:.1f}%")
        col3.metric("Cloud", f"{cloud:.1f}%")

        # COLOR PALETTE
        h = normalize(temp, -5, 35)
        s = normalize(humidity, 20, 100)
        l = 0.3 + normalize(cloud, 0, 100) * 0.4

        palette = []
        for i in range(5):
            h2 = (h + i*0.12) % 1.0
            palette.append(colorsys.hls_to_rgb(h2, l, s))

        st.subheader("Memory Palette")
        fig, ax = plt.subplots(figsize=(4, 1))
        for i, c in enumerate(palette):
            ax.add_patch(Rectangle((i, 0), 1, 1, color=c))
        ax.set_xlim(0, 5)
        ax.axis("off")
        st.pyplot(fig)

        # GENERATIVE POSTER
        st.subheader("Weather-Based Generative Poster")

        random.seed(seed)
        np.random.seed(seed)

        fig2, ax2 = plt.subplots(figsize=(6, 9))
        ax2.set_facecolor("black")
        ax2.set_xlim(0, 1)
        ax2.set_ylim(0, 1)
        ax2.axis("off")

        complexity = int(30 + humidity/3 + cloud/4)

        for _ in range(complexity):
            color = random.choice(palette)
            cx, cy = np.random.rand(), np.random.rand()
            size = 0.03 + normalize(temp, -5, 35) * 0.15

            if random.random() < 0.55:
                shape = Circle((cx, cy), size, color=color, alpha=0.8)
            else:
                w = size * np.random.uniform(0.4, 1.6)
                h_ = size * np.random.uniform(0.4, 1.6)
                angle = random.random() * 360
                shape = Ellipse((cx, cy), w, h_, angle=angle,
                                color=color, alpha=0.8)
            ax2.add_patch(shape)

        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=200, bbox_inches="tight")
        buf.seek(0)
        plt.close()

        st.image(buf, caption=f"Memory Poster for {city}", use_container_width=True)

        st.download_button(
            "Download Memory Poster",
            buf,
            file_name=f"memory_atlas_{city}.png",
            mime="image/png"
        )
