# app.py
# ------------------------------------------
# Streamlit Multipage: VoicePainter + Memory Atlas
# ------------------------------------------

import io
import random
import colorsys
import requests
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import librosa

from matplotlib.patches import Circle, Ellipse, Polygon, Rectangle


# =========================================================
# CONFIG
# =========================================================
st.set_page_config(
    page_title="Creative Data Studio",
    page_icon="🎨",
    layout="wide"
)

# =========================================================
# SIDEBAR (공통)
# =========================================================
st.sidebar.title("🌐 Navigation")
page = st.sidebar.radio(
    "Select a page",
    ("Home", "🎤 VoicePainter", "🌈 Memory Atlas")
)

# API 입력 (Memory Atlas에서 사용)
st.sidebar.markdown("---")
st.sidebar.subheader("🔧 API Settings")
api_base = st.sidebar.text_input(
    "Open-Meteo API (Optional, default used if empty)",
    value="https://api.open-meteo.com/v1/forecast"
)

st.sidebar.markdown(
    """
    **This app includes:**
    - Voice-based generative posters  
    - Weather → color → generative art  
    - Audio feature extraction  
    - Data-driven creativity  
    """
)


# =========================================================
# 🔹 COMMON UTILS
# =========================================================
def normalize(v, a, b):
    return float(np.clip((v - a) / (b - a + 1e-8), 0, 1))


# =========================================================
# 🔹 PAGE: HOME
# =========================================================
if page == "Home":
    st.title("🎨 Creative Data Studio")
    st.subheader("Art generated by Voice & Weather Data")

    st.markdown(
        """
        This project combines **Generative Art**, **Data Visualization**,  
        **Audio Processing**, and **Web Interaction** into one creative platform.

        ### 📌 Features:
        - **VoicePainter**: Draw with your voice  
        - **Memory Atlas**: Visualize each day as a color palette  
        - Data → Color → Art transformation  
        - Built with Streamlit + Python  
        """
    )

    st.image(
        "https://images.unsplash.com/photo-1500534623283-312aade485b7",
        caption="Data-driven Creativity",
        use_container_width=True
    )

# =========================================================
# 🔹 PAGE: VOICEPAINTER
# =========================================================
elif page == "🎤 VoicePainter":
    st.title("🎤 VoicePainter: Draw With Your Voice")

    # -----------------------------
    # 파일 업로드
    uploaded = st.file_uploader("Upload voice file (wav/mp3/m4a)", 
                                type=["wav", "mp3", "m4a"])

    seed = st.slider("Poster variation seed", 0, 9999, 42)

    # -----------------------------
    # 특징 추출 함수
    def extract_audio_features(file):
        y, sr = librosa.load(file, sr=None, mono=True)

        if len(y) > 10 * sr:
            y = y[:10 * sr]

        rms = librosa.feature.rms(y=y)[0].mean()
        zcr = librosa.feature.zero_crossing_rate(y)[0].mean()
        centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0].mean()
        tempo, _ = librosa.beat.beat_track(y=y, sr=sr)

        try:
            f0 = librosa.yin(
                y,
                fmin=librosa.note_to_hz("C2"),
                fmax=librosa.note_to_hz("C7"),
            )
            pitch = float(np.nanmean(f0))
        except:
            pitch = 0.0

        return {
            "sr": sr,
            "pitch": pitch,
            "rms": rms,
            "zcr": zcr,
            "centroid": centroid,
            "tempo": float(tempo),
        }

    # -----------------------------
    # color palette
    def features_to_palette(f, n=5):
        p = normalize(f["pitch"], 80, 800)
        l = 0.3 + normalize(f["rms"], 0, 0.1) * 0.4
        s = 0.4 + normalize(f["centroid"], 500, 5000) * 0.5
        t = normalize(f["tempo"], 40, 180)
        z = normalize(f["zcr"], 0, 0.3)

        palette = []
        for i in range(n):
            h = (p + i * 0.12 + t * 0.3) % 1.0
            s2 = np.clip(s + (i - n//2) * 0.05, 0.2, 0.95)
            l2 = np.clip(l + (z - 0.5) * 0.2 + (i - n//2) * 0.03, 0.2, 0.85)
            palette.append(colorsys.hls_to_rgb(h, l2, s2))
        return palette

    # -----------------------------
    # Generative poster
    def draw_poster(features, palette, seed):
        random.seed(seed)
        np.random.seed(seed)

        fig, ax = plt.subplots(figsize=(6, 9))
        ax.set_facecolor("black")
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        n = int(30 + normalize(features["rms"], 0, 0.1) * 40)
        for _ in range(n):
            color = random.choice(palette)
            cx = np.random.rand()
            cy = np.random.rand()
            r = np.random.uniform(0.03, 0.18)

            if random.random() < 0.5:
                shape = Circle((cx, cy), r, color=color, alpha=0.8)
            else:
                w = r * np.random.uniform(0.3, 1.2)
                h = r * np.random.uniform(0.3, 1.2)
                angle = random.random() * 360
                shape = Ellipse((cx, cy), w, h, angle=angle,
                                color=color, alpha=0.8)

            ax.add_patch(shape)

        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=200, bbox_inches="tight")
        buf.seek(0)
        plt.close()
        return buf

    # -----------------------------
    # PROCESS
    if uploaded:
        st.audio(uploaded)
        uploaded.seek(0)

        f = extract_audio_features(uploaded)
        st.subheader("Extracted Audio Features")
        st.write(f)

        palette = features_to_palette(f)

        # Palette preview
        st.subheader("Generated Color Palette")
        fig, ax = plt.subplots(figsize=(4, 1))
        for i, c in enumerate(palette):
            ax.add_patch(Rectangle((i, 0), 1, 1, color=c))
        ax.set_xlim(0, len(palette))
        ax.set_ylim(0, 1)
        ax.axis("off")
        st.pyplot(fig)

        # Poster
        st.subheader("Your Voice Poster")
        poster = draw_poster(f, palette, seed)
        st.image(poster)

        st.download_button("Download Poster", poster, "voice_poster.png")

    else:
        st.info("Upload a voice file to begin.")


# =========================================================
# 🔹 PAGE: MEMORY ATLAS
# =========================================================
elif page == "🌈 Memory Atlas":
    st.title("🌈 Memory Atlas: Weather → Color → Art")

    city = st.text_input("City Name (English)", "Seoul")
    date = st.date_input("Select a date")

    if st.button("Generate Memory Palette"):
        st.subheader("Weather Data → Colors")

        # -------------------------
        # API 요청
        url = f"{api_base}?latitude=37.5665&longitude=126.9780&hourly=temperature_2m,relativehumidity_2m,cloudcover&timezone=Asia%2FSeoul"

        data = requests.get(url).json()

        temp = np.mean(data["hourly"]["temperature_2m"])
        humidity = np.mean(data["hourly"]["relativehumidity_2m"])
        cloud = np.mean(data["hourly"]["cloudcover"])

        st.write(f"🌡 Temperature: {temp:.1f}°C")
        st.write(f"💧 Humidity: {humidity:.1f}%")
        st.write(f"☁️ Cloud: {cloud:.1f}%")

        # data → color
        h = normalize(temp, -5, 35)
        s = normalize(humidity, 20, 100)
        l = 0.3 + normalize(cloud, 0, 100) * 0.4

        palette = []
        for i in range(5):
            h2 = (h + i * 0.1) % 1.0
            rgb = colorsys.hls_to_rgb(h2, l, s)
            palette.append(rgb)

        st.subheader("🎨 Memory Palette")
        fig, ax = plt.subplots(figsize=(4, 1))
        for i, c in enumerate(palette):
            ax.add_patch(Rectangle((i, 0), 1, 1, color=c))
        ax.set_xlim(0, 5)
        ax.set_ylim(0, 1)
        ax.axis("off")
        st.pyplot(fig)

        st.success("Your Memory Palette has been generated!")

